site_name: ValidusEduTech

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - python
  nav_style: dark

nav:
  - Index: "index.md"
  - Introduction: "introduction.md"
  - Syllabus: "syllabus.md"





copyright: |
  &copy; 2023 <a href="https://github.com/anandkhandekar"  target="_blank" rel="noopener">Anand Khandekar</a>
